name: sqlproxy-ssh-tunnel
image: berylcc/sqlproxy-ssh-tunnel:1.0.1-rc.0
# imagePullSecrets: "my-docker-repo-secret"
authorizedKeysBase64: "nice long base64 encoded string of authorized_keys"
hostKeyBase64: "nice long base64 encoded string of host key"

cloudsql:
  useWorkloadIdentity: false
  serviceAccountName: "sqlproxy-workload-identity"
  serviceAccountKeyBase64: "nice long base64 encoded of Google service account JSON - if not using workload identity"
  instances:
    - instance: "sql_instance"
      project: "my-project"
      region: "us-west1"
      port: 3306

service:
  loadBalancerPort: 22
  # loadBalancerIP: 10.0.0.1

# reverseTunnel:
#   privateKeyBase64: "base64 encoded string of client private key"
#   sshUser: sshuser
#   sshHost: ssh.example.com
#   remoteDbPort: 3306
#   localDbPort: 3306

sshd_config: |-
  GatewayPorts no
  X11Forwarding no
  AuthorizedKeysFile .ssh/authorized_keys
  HostKey /etc/ssh/ssh_host_ed25519_key
  PermitRootLogin no
  PasswordAuthentication no
  AuthenticationMethods publickey

  # LogLevel DEBUG1

  Match User sshuser
    AllowTcpForwarding yes
    MaxAuthTries 10
    MaxSessions 100
