name: sqlproxy-ssh-tunnel
image: berylcc/sqlproxy-ssh-tunnel:1.0
# imagePullSecrets: "my-docker-repo-secret"
authorizedKeysBase64: "nice long base64 encoded string of authorized_keys"
hostKeyBase64: "nice long base64 encoded string of host key"

cloudsql:
  project: "my-project"
  region: "us-west1"
  instance: "sql_instance"
  port: 3306
  serviceAccountKeyBase64: "nice long base64 encoded of Google service account JSON"

service:
  loadBalancerPort: 22
  # loadBalancerIP: 10.0.0.1
