apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: 1
  template:
    metadata:
      name: {{.Values.name}}
      labels:
        app: {{.Values.name}}
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image}}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
          ports:
            - containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: authorized-keys
              mountPath: /home/sshuser/.ssh
              subPath: authorized_keys
              readOnly: true
            - name: server-key
              mountPath: /etc/ssh/ssh_host_ecdsa_key
              subPath: ssh_host_ecdsa_key
              readOnly: true
            - name: sshd-config
              mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
              readOnly: true
        - name: sqlproxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17-alpine
          command:
            [
              "/cloud_sql_proxy",
              "-instances={{.Values.cloudsql.project}}:{{.Values.cloudsql.region}}:{{.Values.cloudsql.instance}}=tcp:{{.Values.cloudsql.port}}",
              "-credential_file=/secrets/cloudsql/sql_credentials.json",
            ]
          volumeMounts:
            - name: sqlproxy-credential
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: sshd-config
          configMap:
            name: sshd-config
        - name: sqlproxy-credential
          secret:
            secretName: sqlproxy-credential
        - name: authorized-keys
          defaultMode: 0600
          secret:
            secretName: authorized-keys
        - name: server-key
          defaultMode: 0600
          secret:
            secretName: server-key
