apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: 1
  template:
    metadata:
      name: {{.Values.name}}
      labels:
        app: {{.Values.name}}
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image}}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1m
              memory: 10Mi
          ports:
            - containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: authorized-keys
              mountPath: /home/sshuser/.ssh/authorized_keys_temp
              subPath: authorized_keys
              readOnly: true
            - name: server-key
              mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: ssh_host_ed25519_key
              readOnly: true
            - name: sshd-config
              mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
              readOnly: true
        - name: sqlproxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17-alpine
          command:
            - /cloud_sql_proxy
            - -instances={{- range .Values.cloudsql.instances -}}
                           {{ .project }}:{{ .region }}:{{ .instance }}=tcp:0.0.0.0:{{ .port }},
                         {{- end }}
            - -credential_file=/secrets/cloudsql/sql_credentials.json
          volumeMounts:
            - name: sqlproxy-credential
              mountPath: /secrets/cloudsql
              readOnly: true
{{- if .Values.reverseTunnel }}
        - name: reverse-tunnel
          image: {{.Values.image}}
          imagePullPolicy: Always
          command:
            - autossh
            - -M
            - "0"
            - -f
            - -N
            - -R
            - "{{.Values.reverseTunnel.remoteDbPort}}:{{.Values.reverseTunnel.localDbHost}}:{{.Values.reverseTunnel.localDbPort}}"
            - "{{.Values.reverseTunnel.sshUser}}@{{.Values.reverseTunnel.sshHost}}"
            - -g
            - -i
            - <PATH_TO_PRIVATE_KEY>
            - -o
            - ServerAliveInterval=10
            - -o
            - ServerAliveCountMax=1
            - -o
            - ExitOnForwardFailure=yes
            - -o
            - StrictHostKeyChecking=accept-new
          volumeMounts:
            - name: reverse-tunnel-private-key
              mountPath: /root/reverse_tunnel_ed25519
              subPath: reverse_tunnel_ed25519
              readOnly: true
{{- end }}
      volumes:
        - name: sshd-config
          configMap:
            name: sshd-config
        - name: sqlproxy-credential
          secret:
            secretName: sqlproxy-credential
        - name: authorized-keys
          secret:
            defaultMode: 0600
            secretName: authorized-keys
        - name: server-key
          secret:
            defaultMode: 0600
            secretName: server-key
        - name: reverse-tunnel-private-key
          secret:
            defaultMode: 0600
            secretName: reverse-tunnel-private-key
