apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: ssh
      port: {{ .Values.service.loadBalancerPort }}
      targetPort: 22
  selector:
    app: {{.Values.name}}
  type: "LoadBalancer"
  externalTrafficPolicy: Local
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}