apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  ports:
    - name: ssh
      port: {{ .Values.service.loadBalancerPort }}
      targetPort: 22
  selector:
    app: {{.Values.name}}
  type: LoadBalancer
  externalTrafficPolicy: Local
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.sourceRanges }}
  loadBalancerSourceRanges: 
    {{- range .Values.service.sourceRanges }}
    - {{ . }}
    {{- end }}
{{- end }}
