{{- if not .Values.useWorkloadIdentity }}
apiVersion: v1
kind: Secret
metadata:
  name: sqlproxy-credential
type: Opaque
data:
  sql_credentials.json: {{.Values.cloudsql.serviceAccountKeyBase64}}
{{- end }}