apiVersion: v1
kind: ConfigMap
metadata:
  name: sshd-config
data:
  sshd_config: |-
    GatewayPorts no
    X11Forwarding no
    AuthorizedKeysFile	.ssh/authorized_keys
    HostKey /etc/ssh/ssh_host_ecdsa_key
    PermitRootLogin no
    PasswordAuthentication no
    AuthenticationMethods publickey

    LogLevel DEBUG1

    Match User sshuser
      AllowTcpForwarding yes
      MaxAuthTries 10
      MaxSessions 100
